[PD-7085] links for sort by
DirectEmployers/microsite-js pull request #100
Opened 2021-03-18 14:54 UTC by nate998877

## What does this PR do?
Changes the sort by options to use links instead of click events on list items. Also updated links to be new format rather than query strings.

## Notes to Reviewer
N/A

2021-03-19 13:32 UTC, jeremytubbs requested changes
I left a comment with a simpler solution and there was a bug.

- changing sort should reset the page to 1

2021-03-19 13:32 UTC, jeremytubbs commented on src/pages/jobs.vue
> +                                        </g-link>
Guess what you can do just this?
```
<g-link
    :to="{
        path: $route.path,
        query: { ...$route.query, sort: option.toLowerCase(), page: 1 }
    }"
>
    {{ option }}
</g-link>
```
no changes to provider required

2021-03-22 14:13 UTC, jeremytubbs approved these changes

2021-03-22 16:27 UTC, jeremytubbs approved these changes

2021-03-22 16:28 UTC, surgiie approved these changes

2021-03-22 16:29 UTC, merged