[PD-7025] solr endpoint services
DirectEmployers/microsite-js pull request #130
Opened 2021-05-07 19:11 UTC by nate998877

## What does this PR do?
Adds services for solr endpoints

## Notes to Reviewer
Doesn't use new service, just introduces them and refactors services. You can test them by changing searchService in provider to filterSearchService or jobSearchService

2021-05-07 20:13 UTC, surgiie requested changes

2021-05-07 20:13 UTC, surgiie commented on src/services/search.js
> +    if (process.isClient) {
Rework this back to what it was or builds fail:

https://github.com/DirectEmployers/microsite-js/pull/128

2021-05-10 22:49 UTC, surgiie requested changes

2021-05-10 22:49 UTC, surgiie commented on src/services/search.js
> +    if (!process.isClient || (isDevelopment()) && window.location.hostname == 'localhost') {
The if is still off a little bit:

It shoule be:

`if (!process.isClient || (isDevelopment() && window.location.hostname == 'localhost')){`

The close parenthesis `)` on `isDevelopment` belongs at the end of  of the if

2021-05-10 23:11 UTC, surgiie requested changes

2021-05-10 23:11 UTC, surgiie commented on src/services/search.js
>  export function commuteSearchService(input, config) {
Pretty sure `commuteSearchService` can be made generic to use `apiService` as well

2021-05-17 20:55 UTC, jeremytubbs commented on src/services/search.js
> +export function jobsSearchService(input, config) {
make these singular `jobSearchService` and `filterSearchService`

2021-05-17 20:55 UTC, surgiie requested changes

2021-05-17 20:55 UTC, surgiie commented on src/services/search.js
> +    const endpoint = path_is_endpoint ? path : `${source}/${path}`
Imo id rather see us move to accepting the endpoint instead of adding this new parameter


```js
export function searchService(input, config) {
    const source = kebabCase(config.source)
    return apiService(input, config, `${source}/${path}`)
}

```

2021-05-17 20:55 UTC, jeremytubbs requested changes
Could you update the config to use a solr config?

2021-05-17 21:03 UTC, jeremytubbs commented on src/services/search.js
> +    const endpoint = path_is_endpoint ? path : `${source}/${path}`
just move the path calculation back the the individual services

2021-05-18 14:54 UTC, jeremytubbs approved these changes

2021-05-18 14:55 UTC, jeremytubbs approved these changes

2021-05-19 15:15 UTC, surgiie approved these changes

2021-05-19 15:20 UTC, merged