military base component
DirectEmployers/microsite-js pull request #155
Opened 2021-09-10 12:45 UTC by surgiie

## What does this PR do?
* Consolidate military base map example into a microsite-js component.

2021-09-10 14:32 UTC, nate998877 commented on src/components/Search/Maps/MilitaryBaseMap.vue
> +        },
If you search for each branch individually or sort bases by branch you can avoid re-doing a search every time you toggle a branch. Only re-do the search when non-branch filter options change.

2021-09-10 17:03 UTC, surgiie commented
Closing to do some more work per PR feedback

2021-09-10 17:50 UTC, nate998877 approved these changes

2021-09-20 10:41 UTC, jeremytubbs requested changes
This works the opposite of how I would expect it... I think it should be a single selection not a multiple selection. 
Currently selecting a filter option removes it from the map, I think it should select that one and remove all others from the map. We can discuss with RR today.

2021-09-20 18:23 UTC, nate998877 approved these changes

2021-09-22 00:45 UTC, jeremytubbs approved these changes

2021-09-22 00:54 UTC, merged