[PD-7461] - job detail lighthouse
DirectEmployers/microsite-js pull request #159
Opened 2021-09-27 20:46 UTC by jeremytubbs

## What does this PR do?
Component changes to be moved to site-template for job detail pages. 
- uses router methods beforeRouteUpdate and beforeRouteEnter to load job json from s3 before page load
- change .env files to not be git ignored
- switching configs requires updating the s3 folder in .env if we want job detail pages to work
- removes jobDetail and jobExpired
- adds a footer so we can see CLS

## Notes to Reviewer
This is only updating the job detail page.. it does not update the search page which will eventually use the same demo searchForm.

2021-09-27 21:43 UTC, surgiie requested changes
Made some comments about changes, most of them can be left for another PR as they are picky/code cleanup, ive documented them in the review for future reference.

2021-09-27 21:43 UTC, surgiie commented on .env.production
> +GRIDSOME_USE_MINIKUBE=false
This repo doesnt deploy, doesnt seem like we need this file?

2021-09-27 21:43 UTC, surgiie commented on src/components/ApplyButton.vue
> +                return {vs: sessionStorage.getItem("vs")}
The `"~/services/storage"` service contains a `VS_KEY` constant you can utilize here.

2021-09-27 21:43 UTC, surgiie commented on src/mixins/formatLocationParam.js
> +export default {
For the most part im okay with this mixin. 

However i have some slight concerns about opening up the door for code repetition.

Personally i think combining this mixin and and the moc one into a `~/mixins/formatRouteParams.js` seems like a good improvement cause they both duplicate the `isSlug` function.

Secondly, im not sure i like that it enforces the component utilizing it to have a `this.formData` property. IMO changing the `formatLocationParam` to accept the location as an argument would allow reuse of the function/mixin outside of the search form. So it could compute the formatted value and then it is not explicitly meant for the search form component only, it could be used for other components. For example it can be used in another component to format the location active filter/chip  on listing or job detail pages that have active filters.

2021-09-27 21:43 UTC, surgiie commented on src/mixins/searchForm.js
> +    created() {
The created and watch function have  the same logic, only difference is the the object being used to update the data. You can reduce the duplication here by extracting this logic to a  function that accepts the data to use to set the form data, ie:

```js
created(){
    this.initData({...this.$route.query, ...this.$route.params})
},
watch:{
    $route(newData){
        this.initData({...newData.query, ...newData.params})
    },
},
methods:{
   ...
   initData(routeData){ // or whatever you feel is name appropriate
       this.setDefaultFormData()
       this.updateFormData(routeData)
       this.formatLocationParam()
       this.formatMocParam()
  
   }
}

```

2021-09-27 21:43 UTC, surgiie commented on src/templates/Job.vue
> +        schema() {
This schema is pretty much the same on every site. We could wrap this into a exportable function if we wanted? 

So from Zarif's end: 

`getJobSchemaData(job, customData)`

This just merges this default with anything custom RR passes in?

2021-09-27 21:43 UTC, surgiie commented on src/mixins/searchForm.js
> +        mergeObjects(obj1, obj2) {
This function name is confusing for what the function actually does:

![image](https://user-images.githubusercontent.com/12025002/134989022-36aa12b6-4e55-442d-ab41-264695cc77f0.png)

This function overwrites key/values in object 1 that were set in object 2 key and throws away/doesnt merge keys in object 2 if they dont exist in object 1. `mergeSameKeysInto(src, from)` or something different would make it more clear what this does?

2021-09-27 22:14 UTC, jeremytubbs commented on src/mixins/searchForm.js
> +        mergeObjects(obj1, obj2) {
not sure what to rename this.. ignoring for now

2021-09-27 22:15 UTC, jeremytubbs commented on src/templates/Job.vue
> +        schema() {
not sure.. I am going to leave it outside of our code so it is easy to change.

2021-09-28 13:39 UTC, surgiie approved these changes

2021-09-28 13:54 UTC, merged