pd 7468 radius search input
DirectEmployers/microsite-js pull request #162
Opened 2021-10-01 18:25 UTC by surgiie

## What does this PR do?

### Release notes
RRR Fixed a bug in an app...

## Notes to Reviewer

## Document Changes

2021-10-04 20:46 UTC, jeremytubbs requested changes
Minor changes

2021-10-04 20:46 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +        <div :class="hasAddOns ? 'form__input-group': ''">
change to `:class="{'form__input-group': hasAddOns}"`

2021-10-04 20:46 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +            this.$emit('blur', event.target.value)
Need to run a formatter.

`this.$emit("blur", event.target.value)`

2021-10-04 20:46 UTC, jeremytubbs commented on src/demo/components/SearchForm.vue
> +                    @setResult="search"
please remove `@setResult` the user doesn't get a chance to select the radius

2021-10-05 15:33 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +                ref="input"
I don't like sorting things by length.. I think keeping them grouped is better.

2021-10-05 15:33 UTC, jeremytubbs approved these changes

2021-10-05 16:40 UTC, nate998877 approved these changes

2021-10-05 16:54 UTC, merged