[PD-7571] Autocomplete inputs autocompletes
DirectEmployers/microsite-js pull request #188
Opened 2021-11-03 14:39 UTC by nate998877

## What does this PR do?
When navigating using up/down/tab/enter the current index of the results should appear in the input & should be set as the search input when tabbing/entering. Entering worked as expected, but not up/down navigation. This PR fixes the up/down issues.

## Notes to Reviewer
To view the functionality I'm referring use the autocompleteinput @ http://localhost:8080 on qc and type in anything that returns autocomplete results eg "ind" in the location & use up/down arrows. Then checkout this branch and do the same. Notice how the display value changes where it didn't on qc.

2021-11-03 21:41 UTC, jeremytubbs requested changes
I really like this functionality.. just some small code changes required.

2021-11-03 21:41 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +            if(this.selectedIndex == this.results.length){
move to a separate method.. maybe named `resetUserInput` also if you just set `this.holder=this.value` you can just do once in `setValue({display: this.holder)` rather than throughout the code

2021-11-03 21:41 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +        tabDown(){
can be removed

2021-11-03 21:41 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +                @keydown.tab="tabDown"
can be removed

2021-11-03 21:41 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +            holder: ""
rename to `userInput`

2021-11-03 21:41 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +            this.holder = {display:value}
change to `this.userInput = value`

2021-11-03 21:41 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +            this.holder={display:this.value}
can be removed

2021-11-03 21:43 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
>              this.scroll()
call `shouldResetUserInput()` before scroll

2021-11-04 16:11 UTC, surgiie requested changes
Works perfect and i like these changes as well! However, im personally not a fan of the `shouldResetUserInput()` name because its naming implies it returns a boolean or should be used in a if statement. 

Consider removing the `should` word from it if were calling the function as is. `i.e this.resetUserInput()`

2021-11-08 19:37 UTC, zarifrahat approved these changes

2021-11-08 20:41 UTC, jeremytubbs approved these changes

2021-11-08 21:40 UTC, surgiie approved these changes

2021-11-08 21:54 UTC, merged