[PD-7657] - add allow blank search prop
DirectEmployers/microsite-js pull request #205
Opened 2021-11-29 21:18 UTC by surgiie

## What does this PR do?
* Add a new prop that signals provider whether or not a blank search is allowed.

2021-11-29 21:44 UTC, jeremytubbs commented on src/components/Search/AppProvider.vue
> +            if(this.requireKeyword && !searchData.q){
update this to check for any type of "query" data

2021-11-29 22:40 UTC, surgiie commented on src/components/Search/AppProvider.vue
> +            if(this.requireKeyword && !searchData.q){
Believe the code ive implemented will now prevent a blank search if specified.

2021-11-30 17:30 UTC, jeremytubbs requested changes

2021-11-30 17:30 UTC, jeremytubbs commented on src/components/Search/AppProvider.vue
> +            let data = omit(this.searchData, ["page", "num_items", "sort", "offset", "r"])
this can be updated to 
```
            let data = omit(this.searchData, ["page", "num_items", "sort", "offset", "r"])
            if (! isEmpty(data)) {
                return true
            }
```

2021-11-30 17:30 UTC, jeremytubbs commented on src/components/Search/AppProvider.vue
>          extraFilterData: {
`extraFilterData` is not used

2021-11-30 19:05 UTC, jeremytubbs approved these changes

2021-11-30 19:14 UTC, merged