scale icon on zoom in military map
DirectEmployers/microsite-js pull request #206
Opened 2021-11-30 19:49 UTC by surgiie

## What does this PR do?
* Add event handler for resizing icons on zoom.

##

Kudos to: https://stackoverflow.com/questions/3281524/resize-markers-depending-on-zoom-google-maps-v3

2021-12-01 14:29 UTC, nate998877 commented on src/components/Search/Maps/AppMilitaryBaseMap.vue
> +        },
I would like to see the math here changed. 100px is a good max, but 2px is too small for a minimum. It's just black dots. 

I think 15px is a good minimum, but the specifics on that don't matter. I would just like to be able to differentiate icons even if you can't identify them. I also think the size should change linearly. The current math causes the icons to be way too large & when zooming in 1 then 1 out causes the icon to be a different size than they start with.

I've found 
pixelSizeAtZoom0 = 15;
iconSize=35;  //set in data
Math.round(pixelSizeAtZoom0+zoom*5);
gives good sizes throughout.

This isn't a perfect solution as it hard codes the icon sizes for a given zoom level & the default size won't line up if you change the default zoom level. If we care about that I think a conversation needs to be had about the full extent of what this should handle & how much we expose to RR.

2021-12-01 15:12 UTC, surgiie commented on src/components/Search/Maps/AppMilitaryBaseMap.vue
> +        },
Implemented this logic.

2021-12-01 15:21 UTC, nate998877 approved these changes

2021-12-06 15:59 UTC, jeremytubbs requested changes

2021-12-06 15:59 UTC, jeremytubbs commented on src/components/Search/Maps/AppMilitaryBaseMap.vue
> +            let pixelSizeAtZoom0 = 15; //the size of the icon at zoom level 0
can we make both of these props with default values?

2021-12-07 16:20 UTC, jeremytubbs approved these changes

2021-12-07 16:34 UTC, merged