[PD-7727] featured_jobs updates in response object
DirectEmployers/microsite-js pull request #226
Opened 2022-01-10 13:15 UTC by nate998877

## What does this PR do?
Response object passed to the template should include updates to featured jobs. It currently does not. This PR fixes this.

2022-01-11 15:27 UTC, surgiie requested changes

2022-01-11 15:27 UTC, surgiie commented on src/components/Search/AppProvider.vue
> +                        if (r.data.pagination.page == 1) {
Unsure of what this solves. Why would we only update featured jobs on page 1 or else concat them to the main jobs?  Featured jobs shouldnt be concatenated to the main jobs, they should be separate.

2022-01-11 15:27 UTC, surgiie commented on src/components/Search/AppProvider.vue
>                          this.response.jobs = r.data.jobs
I dont like how complicated this function is starting to get with all the if else logic. We're extracing specific properties into `this.response` from `r.data` but we honestly should just be setting the entire response so that we're not restricting anything from Zarif. Just give him control and do `this.response = r.data`

2022-01-11 15:27 UTC, surgiie commented on src/components/Search/AppProvider.vue
>                          this.response.jobs = r.data.jobs
The last else seems redundant too. Remove it.

2022-01-12 22:56 UTC, surgiie requested changes

2022-01-12 22:56 UTC, surgiie commented on src/components/Search/AppProvider.vue
> +                    r.data.featured_jobs.map(x => (x.featuredJob = true))
I prefer if this was called `isFeatured` to be consistent with its boolean type.

2022-01-25 20:02 UTC, surgiie approved these changes

2022-02-04 14:38 UTC, jeremytubbs approved these changes

2022-02-04 15:06 UTC, merged