[PD-7809] map markers
DirectEmployers/microsite-js pull request #233
Opened 2022-03-08 15:04 UTC by nate998877

## What does this PR do?
Merges the 4 map components that previously existed into one. With the goal of creating one place to add bug fixes & extend functionality. The existing military & job maps have diverged from each other regarding features & functionality. 

## Notes to Reviewer
Testing/ examples available at https://github.com/DirectEmployers/microsite-template/tree/map-example

Please ensure `NUXT_ENV_GM_API_KEY` is set inside .env.development in the template. Otherwise you will receive 500 errors

2022-03-08 16:38 UTC, surgiie requested changes

2022-03-08 16:38 UTC, surgiie commented on src/components/Search/Maps/AppMap.vue
> +            marker.icon = "https://frontdoor.jobs/favicon.ico"
This shouldnt be hard coded to a specific company.

2022-03-08 16:53 UTC, surgiie requested changes
Minor code changes noted. Will re-review when PR/example is ready.

2022-03-28 18:53 UTC, surgiie requested changes

2022-03-28 18:53 UTC, surgiie commented on src/components/Search/Maps/AppMilitaryMap.vue
> +{
Dont think you meant to leave this here?

2022-04-06 16:08 UTC, surgiie requested changes
* Clicking on a job map marker in your template example doesnt navigate to search page
* Im a bit hesistant to merge because of the use of "Extends" im under the impression this is not available or discouraged in vue 3.
* Your military example is also broken so unable to test that map:

![image](https://user-images.githubusercontent.com/12025002/162018963-afddeb46-05f8-4a4d-b48a-394ca077d83a.png)

* I would also prefer that @zarifrahat plays around with these examples, particularly the military one once its working since he is using it on sites currently.

2022-04-08 17:32 UTC, nate998877 commented
> * Clicking on a job map marker in your template example doesnt navigate to search page
> * Im a bit hesistant to merge because of the use of "Extends" im under the impression this is not available or discouraged in vue 3.
> * Your military example is also broken so unable to test that map:
> * I would also prefer that @zarifrahat plays around with these examples, particularly the military one once its working since he is using it on sites currently.

All of the maps work, it appears you maybe were missing an API key, I updated the comments to reflect that. I thought we all had API keys already set.

The job map has been updated to fix the navigation issues.

Zarif defiantly needs to play with these & I have added him as a reviewer.

2022-04-13 16:34 UTC, zarifrahat approved these changes

2022-04-14 18:48 UTC, surgiie approved these changes

2022-04-20 16:18 UTC, jeremytubbs approved these changes

2022-04-20 16:18 UTC, merged