[PD-7766] smart radius search
DirectEmployers/microsite-js pull request #237
Opened 2022-03-17 20:24 UTC by nate998877

## What does this PR do?
Updates the AppAutocompleteinput component to better handle showing the radius search option.

## Notes to Reviewer
shouldShowRadius covers several explicit checks for radius search including.

- Your Location
- Autocomplete option selected
- User inputs location with `city, xx` format.
Note, I did add the option for `city, XXX` for instances such as 'New York, USA'. This is controlled via `\w{2,3}` in the regex section.

The updates made to this.result and option are to allow shouldShowRadius know whether the current input is related to a dropdown selection or not. 

## Document Changes
PR - https://github.com/DirectEmployers/microsite-v2-docs/pull/11

2022-03-22 12:47 UTC, jeremytubbs requested changes

2022-03-22 12:47 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +            <slot name="add-on-end" :loading="loading" :shouldShowRadius="shouldShowRadius"></slot>
I don't think we should include implementation specific code in the general autocomplete input.. since we have so much extra functionality for Location Autocomplete .. I would suggest we create a new component for LocationAutocomplete that contains all the logic required for Radius select.

2022-03-22 12:47 UTC, jeremytubbs commented on src/components/Form/AppAutocompleteInput.vue
> +        shouldShowRadius(){
Make a new LocationAutocomplete component that uses the AppAutocompleteInput.. it will include `shouldShowRadius` and the computed options for radius that are in microsite-template.

2022-03-24 18:10 UTC, surgiie requested changes
See my comments: https://github.com/DirectEmployers/microsite-template/pull/40#pullrequestreview-920675896

2022-03-25 18:01 UTC, closed without merging

2022-03-28 13:07 UTC, jeremytubbs reviewed
Sorry if I wasn't clear.. I would like us to add a LocationRadiusAutocomplete component that accepts props for the radius options not a mixin.