[PD-6879] autocomplete update
DirectEmployers/microsite-js pull request #320
Opened 2022-08-01 19:19 UTC by nate998877

## What does this PR do?
Adds a new autocomplete service for military base searches by branch. Updates the form mixin to include a default for the militarybase option.

## Notes to Reviewer
Testing branch - https://github.com/DirectEmployers/microsite-template/tree/test-8129
Associated PR - TODO

2022-08-01 21:03 UTC, jeremytubbs requested changes

2022-08-01 21:03 UTC, jeremytubbs commented on src/mixins/searchForm.js
> +    militarybases: "",
I would prefer a shorter name for this query `mb` or instead of `militarybases`.. you will also need to submit the `branch` I as a select input. Setting a branch input could be used for both the autocomplete for military bases and the moc codes when implemented.

2022-08-08 14:59 UTC, surgiie approved these changes

2022-08-08 15:15 UTC, nate998877 commented on src/mixins/searchForm.js
> +    militarybases: "",
Currently, I have the branch defined in the config field https://github.com/DirectEmployers/microsite-template/blob/717422e9cba846665d3bbf20a317fadf7600e07f/openresty-dejobs-org/components/AppSearchForm.vue#L130. I personally believe the moc autocomplete should be handled by the frontend & shouldn't affect this work, but we can have a discussion about that, if needed. Regardless of the result of that conversation, I would prefer to avoid having the input be responsible for updating multiple form bindings.

2022-08-09 13:26 UTC, jeremytubbs commented
closing because not needed.

2022-08-09 13:26 UTC, closed without merging