remove old service
DirectEmployers/microsite-js pull request #329
Opened 2022-08-11 16:28 UTC by surgiie

## What does this PR do?

### Release notes
RRR Fixed a bug in an app...

## Notes to Reviewer

## Document Changes

2022-08-11 16:41 UTC, nate998877 approved these changes

2022-08-11 16:45 UTC, jeremytubbs requested changes

2022-08-11 16:45 UTC, jeremytubbs commented on src/services/filterPaths.js
> +    return customFilters.sort(function (a, b) {
Add a comment.. one reason to extract functionality out to a named method is because it makes the code self documenting.. now I have to look at this code and think.

2022-08-12 13:22 UTC, nate998877 commented on src/services/filterPaths.js
> +    return customFilters.sort(function (a, b) {
Can't we just assign the `customFilters.sort(...)` to some variable `alphabeticalOrderFilters` & return that? Is that not self documenting enough?

2022-08-12 13:51 UTC, jeremytubbs approved these changes

2022-08-12 13:51 UTC, jeremytubbs commented on src/services/filterPaths.js
> +    return customFilters.sort(function (a, b) {
yes that would be fine but a comment is also fine

2022-08-12 17:39 UTC, merged