[PD-8167] opt out trackers
DirectEmployers/microsite-js pull request #338
Opened 2022-08-24 14:03 UTC by nate998877

## What does this PR do?
Blocked by PD-8166. This changes the default load status of trackers.

## Notes to Reviewer
I haven't tested this yet. I believe work needs done on the template as well & so I'm opening this with DNM as 8166 is reviewed & further template work is investigated.

2022-08-26 14:20 UTC, surgiie requested changes
My only concern with changing the key from 2 separate "accepted" and "declined" is that this will force users who have already opted in/out to re-engage with accepting/declining cookie preferences.

2022-08-29 16:42 UTC, nate998877 commented
> My only concern with changing the key from 2 separate "accepted" and "declined" is that this will force users who have already opted in/out to re-engage with accepting/declining cookie preferences.

There's the option to add some conversion code to prevent the this from happening. But is there any real impact by re-prompting & how long do we leave the conversion code?

2022-08-29 18:12 UTC, jeremytubbs requested changes
This branch is appropriately based on QC. It is overwriting recent changes to the `quality-control` branch.

2022-08-29 18:13 UTC, jeremytubbs commented
> My only concern with changing the key from 2 separate "accepted" and "declined" is that this will force users who have already opted in/out to re-engage with accepting/declining cookie preferences.

@surgiie Please elaborate. There was never a need for two separate values and there has never been a way for a user to change their initial selection.

2022-08-29 18:27 UTC, surgiie commented
> > My only concern with changing the key from 2 separate "accepted" and "declined" is that this will force users who have already opted in/out to re-engage with accepting/declining cookie preferences.
> 
> @surgiie Please elaborate. There was never a need for two separate values and there has never been a way for a user to change their initial selection.


Right now, when a user engages with the cookie banner, it will set these keys: 
![image](https://user-images.githubusercontent.com/12025002/187271714-9df05c93-dd49-4879-9edf-3cd5a3c58893.png)


This PR, changes from this to a single key called `responded_cookie_policy` so once a site deploys these changes, a user will have to re-enage with the banner as the code for checking if a user has declined cookie preferences is no longer checking the `declined_cookie_use` key.

2022-08-29 18:30 UTC, jeremytubbs commented
@nate998877 We should keep the single key called `accepted_cookie_use` .. `responded_cookie_policy` is too generic.

2022-08-29 19:06 UTC, jeremytubbs requested changes
Please change the re-engage functionality to not clear the users previous selection and only work at the component level for `showBanner`.

2022-08-29 19:06 UTC, jeremytubbs commented on src/services/storage.js
> +    return localStorage.removeItem(COOKIES_KEY)
We should not `clearCookieUse` the re-engage feature should just be component level and show the banner again allowing the user to change their choice or just show the info and link to the Privacy Policy.

2022-08-31 19:51 UTC, jeremytubbs requested changes
Minor Changes. Nice work!

2022-08-31 19:51 UTC, jeremytubbs commented on src/services/storage.js
> +    clearCookieUse()
It is not necessary to `clearCookieUse` we can just set it.

2022-08-31 19:51 UTC, jeremytubbs commented on src/components/AppCookieConsent.vue
> -            this.declined = false
When the users is re-engaging with the cookie banner and clicking "Accept" a `window.location.reload()` is required for gtag to be enabled. Since you are using the same data prop of `acceptedCookie` to `showBanner()` I am not sure how you can tell if this is a first engagement or re-engagement. The page should not reload on first engagement but should reload on re-engagement.

2022-09-01 13:32 UTC, surgiie approved these changes
Please add the reload page change that Jeremy mentioned. Aside from that, this does appear to be working as expected.

2022-09-01 19:23 UTC, jeremytubbs approved these changes

2022-09-01 19:26 UTC, merged