[PD-8168] report cookie interact events
DirectEmployers/microsite-js pull request #346
Opened 2022-09-06 17:39 UTC by nate998877

## What does this PR do?
Add Google Analytics tracking on cookie banner interact events.

2022-09-09 19:45 UTC, surgiie approved these changes

2022-09-09 19:45 UTC, surgiie commented on src/components/AppCookieConsent.vue
> +            this.$gtag.event(snakeCase(eventName), eventProps)
Is snake cased event names enforced or expected by google? Why not just pass the event names already in snake case?

2022-09-13 13:24 UTC, jeremytubbs requested changes
please add an `event_label` (Title cased),  an `event_category: "Cookies` and `domain: origin` to the event.

2022-09-13 13:24 UTC, jeremytubbs commented on src/components/AppCookieConsent.vue
> +            this.$gtag.event(snakeCase(eventName), eventProps)
No snake case in not required.. we are using it on the Apply Link button because we are also adding an `event_label` which is title cased for display in the GA dashboard.

2022-09-15 16:46 UTC, merged