Break search provider into separate components
DirectEmployers/microsite-js pull request #37
Opened 2020-12-08 19:33 UTC by nate998877

### What does this PR do?
Breaks AppSearchProvider into two separate files AppGoogleTalentSearchProvider and AppSolrSearchProvider

- Replicated functionality of AppSearchProvider Including Solr fallback
- Updated config to use google_talent API (May want to reject/revert)
- Refactored relevant components to use updated providers (App404, Index, jobs)
- change SumbitSearchForm to newSearch and refactored all relevant components as part of the provider breakup now uses emit events to trigger
- removed AppJobDescription from AppJob
- added default value to getSavedTalentSearch in events.js
- refactored SearchService class to use function and removed async await syntax
- refactored CommuteSearchService class to use function and removed async await syntax

## Notes to Reviewer
While minor updates were done in various relevant files. The review should focus on ensuring all functionality was properly ported to the new provider components.

## Future Considerations
- Pull in Vuex
- Break up job wrapper component into separate components
- Refactor services into plain javascript for consistency
- Remove unused components
- Remove location services (Note: possibly unused)

2020-12-09 14:16 UTC, surgiie commented on src/components/Search/Providers/AppGoogleTalentSearchProvider.vue
> +        getCommuteDefaults(){
Looking at this now in more detail, i think you can just remove this function's return to `inputDefaults`?

2020-12-09 16:03 UTC, surgiie commented on src/components/AppChip.vue
> +    <span class="chip" tabindex="0" @click="clickedChip" v-once>
Would it better to add the `v-once` directive on the component directly instead of in the component? 

This gives the implementer more control over whether the component should be rendered only once?

2020-12-09 17:30 UTC, jeremytubbs requested changes
Issue with double section tags being rendered for `AppGoogleTalentSearchProvider` 
![image](https://user-images.githubusercontent.com/548888/101662614-b88f7400-3a17-11eb-89e2-5448a6d18c42.png)
Also renders two nested section tags if I replace with `AppSolrSearchProvider`.

It would be preferred if we used the `<components :is="">` in jobs.vue for example to determine which provider to render and try to change imports to be lazy loaded.  This would make it so we were not nesting solr inside of google_talent when switching the config source. 

```
components: {
    AppGoogleTalentSearchProvider: () => import('./AppGoogleTalentSearchProvider.vue'),
    AppSolrSearchProvider: () => import('./AppSolrSearchProvider.vue')
  }
```

2020-12-11 15:16 UTC, surgiie commented on src/components/Search/Providers/AppGoogleTalentSearchProvider.vue
> +import AppSolrSearchProvider from "./AppSolrSearchProvider"
Unused import.

2020-12-11 15:21 UTC, surgiie requested changes

2020-12-11 15:21 UTC, surgiie commented on src/demo/components/App404.vue
> +                <AppGoogleTalentSearchProvider
Looks like we forgot to update reference here to use `<component>`

2020-12-11 15:40 UTC, jeremytubbs requested changes
Solr fallback / Google talent config issues:
- When I break google talent by changing the "project_id" to an invalid value the front end makes two successful requests to solr for jobs for the fallback data.
- When I break google talent by changing the `tenant_uuid` to be invalid for some reason the search result is still  returns a `200` response with no jobs. 
- When I try to break google_talent by providing no `company_uuids` and providing only and empty array I still get 200 response with jobs from google talent.

All of the above should result in a single request for fallback solr jobs.

2020-12-11 19:02 UTC, nate998877 commented
> Solr fallback / Google talent config issues:
> 
> * When I break google talent by changing the `project_id` to an invalid value the front end makes two successful requests to solr for jobs for the fallback data.
> * When I break google talent by changing the `tenant_uuid` to be invalid for some reason the search result is still  returns a `200` response with no jobs.
> * When I try to break google_talent by providing no `company_uuids` and providing only and empty array I still get 200 response with jobs from google talent.
> 
> All of the above should result in a single request for fallback solr jobs.

* Fixed issue where invalid Project_ID causes two post requests
* Invalid Tenant_uuid issues caused by backend issue. Will resolve in future PR
* Providing no company_uuid and still getting jobs is an intended feature of the API as you might want to return all of a given tenant's jobs without having to specify all of the company's uuids

2020-12-14 15:27 UTC, jeremytubbs commented on src/components/Search/Providers/mixins/provider.js
> +            default: "section",
change this to "div"

2020-12-14 15:57 UTC, jeremytubbs commented on src/components/Search/AppSearchFilter.vue
> +                    <span @click="selectOption(option)">
These should still be links.

2020-12-14 16:20 UTC, jeremytubbs commented on src/pages/jobs.vue
> +                                                <span @click="selectFilter(filter)">
This should also remain a link.

2020-12-14 16:41 UTC, jeremytubbs commented on src/pages/jobs.vue
>                                          name="sort"
`name` is meaningless on an li?

2020-12-14 18:25 UTC, jeremytubbs approved these changes

2020-12-14 18:26 UTC, merged