[PD-7467] commute search
DirectEmployers/microsite-js pull request #387
Opened 2022-11-28 15:34 UTC by nate998877

## What does this PR do?
Bugfixes & logic for commute search

## Notes to Reviewer
The object merging logic over the mergeObject function is required because it filters against a list that can't include the commute query string values.

Associated PRs - https://github.com/DirectEmployers/microsite-template/pull/226

2022-11-29 18:41 UTC, surgiie requested changes

2022-11-29 18:41 UTC, surgiie commented on src/mixins/searchForm.js
> +    beforeMount() {
Is there any benefit to running this in an earlier hook?

2022-11-29 18:41 UTC, surgiie commented on src/mixins/searchForm.js
> +                this.formData = {...this.formData, ...routeData}
I would follow up with @jeremytubbs on this change. This function name is a bit misleading as it merges objects but only merges key/values in the 2nd object that exists as keys in the 1st object, and throws away everything else. Here's an example:


```js
mergeObj({"foo": "bar"}, {"baz": "buzz", "foo": "not-bar"})
// returns {foo: 'not-bar'}
// notice that "baz" key/value was not merged in cause it didnt exist in the first object.
```

Im under the impression @jeremytubbs made this as an intended change for preventing random url slugs/values from being merged into the payload data.

2022-11-29 18:41 UTC, surgiie commented on src/components/Search/AppSearchProvider.vue
> +        isCommuteSearch: {
I thought we wanted to have this be a separate provider. Im not a fan of mixing provider/search source logic like this, considering this is a google talent only thing. Open to discussion, but i would personally prefer to see this be decoupled out into a new provider then the search page should swap between providers depending on the search type.

2022-11-29 21:24 UTC, nate998877 commented on src/scripts/symlink
> +npm link
npm link relies on the package-name defined in the package.json. Which is already `@directemployers/microsite-js`. This is correct. Defining it with `npm link @directemployers/microsite-js` causes npm to nest the package into itself, which eventually causes an OOM error.

2022-11-29 21:30 UTC, nate998877 commented on src/mixins/searchForm.js
> +    beforeMount() {
I believe tt doesn't properly repopulate the form if called after it's been mounted for reasons beyond my comprehension of the vue event lifecycle. Is there a downside to doing it?

2022-11-29 21:32 UTC, nate998877 commented on src/mixins/searchForm.js
> +                this.formData = {...this.formData, ...routeData}
I understand how the method works. This led to an issue where data that is not present in the defaultFormData not being settable on the FormData on page reloads. I assumed the search API would ignore any irrelevant data sent along with the request.

2022-11-30 21:47 UTC, jeremytubbs requested changes
Please extract commute search to a separate provider.

2022-11-30 21:47 UTC, jeremytubbs commented on src/components/Search/AppSearchProvider.vue
> +        isCommuteSearch: {
Yes, this should be a separate provider.

2022-12-13 17:48 UTC, surgiie requested changes

2023-01-12 15:57 UTC, surgiie approved these changes
Approving as the code itself is working and i dont have any specific changes for this feature.

2023-01-18 21:16 UTC, jeremytubbs approved these changes

2023-01-19 15:07 UTC, merged