[PD-6886] load more button pagination
DirectEmployers/microsite-js pull request #47
Opened 2020-12-29 15:25 UTC by nate998877

### What does this PR do?

- Adds a load more button for fetching jobs. shows all jobs on one page
- Pre fetches jobs when using load more

### notes to Reviewer

This goes with backend PR [PD-6928] and will not work properly without those changes.

2020-12-29 16:50 UTC, surgiie commented on src/components/AppLoadMore.vue
> +            Load More
May check with @jeremytubbs on this but i would honestly prefer we move away from providing styles because of how much trouble they have given Zarif. I would prefer that we just give elements some reasonable class names and let Zarif do the styling on his end.

As an example add a `load-more-pagination` class on `nav` and a `load-more-pagination__button` class on  `button`  and then just let Zarif/RR worry about how it should be styled. Again, check with @jeremytubbs or maybe we should discuss this as a team.


Side note and trivial:: Consider adding a `text` prop or wrapping `Load More` in a `<slot>` to allow implementer to customize text.

2020-12-29 16:51 UTC, surgiie commented on src/components/Search/Providers/mixins/provider.js
> +            isFirstLoad: true,
`isFirstLoad` doesnt appear to be used anywhere.

2020-12-29 17:52 UTC, surgiie requested changes
Overall the code is in way better shape than the initial draft.

### Overall thoughts/Future Discussion.
* Not sure im a fan of `pagination_type` being a config option. It has a false sense that changing it will render the appropriate pagination component but it doesnt. The implementer still has to swap in the pagination component type but again maybe this is fine as its not our problem to do this for RR. I understand that is used to tell the back end what paginator type to use but you can accomplish that without a new config option. See comments i made :

https://github.com/DirectEmployers/microsites-search-api/pull/56

* Im inclined to have a single pagination component that is controlled by props. It either is a single "LoadMore" button or it has pages rendered, and then either a `loadMore` or a `pageSelected` event is emited, this allows the component to swap out without any manual intervention,  but maybe thats a bad call. :man_shrugging: 

* Though the code is alot cleaner, im still not sure im a fan of mixing logic for both infinite and  paginated jobs. 


* Without VueX its a bit hard to keep state management clean. Modifying `siteConfig` directly from props is an anti pattern, and im surprised i didnt see any console logs.

### Changes to be made.
Most comments are up to your discretion, but the following should be changed.


* When you switch back to "page" pagination and use `AppPagination` instead, the jobs dont change across pages, they stay the same no matter how many pages you navigate. It is not until you do a page reload with the current page param that you see the appropriate jobs load. I think this because of some missing splice logic on `jobDisplay`, i only saw code for this happening in `created` and not on every search. Tthis is en example result of what i mean about not liking the mix of infinite and paginated searches.

2020-12-29 17:52 UTC, surgiie commented on src/components/Search/Providers/mixins/provider.js
> +            this.siteConfig.num_items = this.siteConfig.MAX_PAGE_SIZE
Not sure if modifying `siteConfig` directly is a good idea. This seems like it could introduce weird bugs since site config is dependent by several components but could be wrong.

2020-12-29 19:04 UTC, jeremytubbs commented on src/components/AppLoadMore.vue
> +            Load More
Yes, we need a more specific class for "load-more-pagination" than just button and there should be an easy way to change the text.

2020-12-29 20:13 UTC, jeremytubbs requested changes

2020-12-29 20:13 UTC, jeremytubbs commented on src/config.js
> +    pagination_type: "load_more", // Options: [load_more, page] load_more uses offset, page uses pages to load more jobs
I would prefer we keep naming consistent with the backend "LimitOffset" and "PageNumber" also change to a pagination object. The whole pagination object should be optional with defaults set on the backend.
```
pagination: {
    num_items: 15,
    type: "LimitOffset"
}
```

2020-12-29 20:13 UTC, jeremytubbs commented on src/config.js
> +    MAX_PAGE_SIZE: 90,
I don't like that we are requesting 90 jobs at a time and slowly displaying them... I would prefer this be a bit smarter and always be just one page request ahead. For example first request would take 30 jobs, each press of the "Load More" button would request 15 more and display the 15 it has already loaded and not displayed.

2020-12-29 20:38 UTC, jeremytubbs commented on src/pages/jobs.vue
> +                                <AppLoadMore
We can easily switch these out if we wanted to do this.
 
```
<AppLoadMore v-if="$siteConfig.pagination_type == 'load_more'" />
<AppPagination v-else />
```
```
components: {
        AppLoadMore: () => import("~/components/AppLoadMore"),
        AppPagination: () => import("~/components/AppPagination"),
}
```

2020-12-30 17:27 UTC, nate998877 commented on src/config.js
> +    MAX_PAGE_SIZE: 90,
This decreases the number of requests that need to be made. The logic is the same if we set it to 30. Is there a specific reason we don't want to fetch more than 1 page?

2020-12-30 17:28 UTC, nate998877 commented on src/config.js
> +    pagination_type: "load_more", // Options: [load_more, page] load_more uses offset, page uses pages to load more jobs
Currently, a default page size needs to be set on the frontend in order to determine how many jobs to display when using with load more. For the time being, I've removed the default page size on the frontend. Should that be added back? Is there a specific reason we can't have it as a requirement for the config?

2020-12-30 19:59 UTC, merged

2021-01-05 17:08 UTC, jeremytubbs reviewed
I also found a bug in offset not being calculated properly on subsequent requests causing duplicate jobs to be rendered. Comments below further simplify the requirements of this task and should make this bug a non-issue. 
- remove max_page_size
- remove pagaination_type from site config
- submit offset as part of data to the search but not part of input

2021-01-05 17:08 UTC, jeremytubbs commented on src/components/Search/Providers/mixins/provider.js
> +            return this.service(this.filterInput(this.input), this.siteConfigClone)
Do not clone the site config but instead spread offset pagination data with the input data.

2021-01-05 17:08 UTC, jeremytubbs commented on src/config.js
> +    },
remove `pagination_type` and put it back to being a prop on the Search Provider. The search provider will add `offset` and optionally `num_items` to the data. If offset is present it will use the OffsetPaginator.  Remove `max_page_size` and just request a new offset each time the Load More button is clicked.