nuxt3 tests
DirectEmployers/microsite-js pull request #557
Opened 2023-08-15 18:04 UTC by surgiie

- blank
- add package.json
- add map cluster mixin
- add files
- module
- update imports
- updates
- update
- extensions
- updates
- update
- wip
- add url helper
- undo
- add files
- wip
- wip
- wip
- update
- wip
- fix
- fixes
- import fixes
- import fixes
- imports
- remove toString
- lodash-es
- import fixes
- import fixes
- files
- bind
- import fix
- import fix
- upgrade axios
- imports
- update import
- remove qs
- imports
- imports
- imports
- update
- wip
- update
- update
- wip
- wip
- missing import
- wip
- key
- imports
- fix
- imports
- update
- fix import
- fix import
- yargs
- wip
- wip
- wip
- update
- wip
- wip
- typo
- update
- wip
- fix
- update
- fix config
- fix
- add showdown
- [build-jobs]
- remove log
- update reference to bucket
- remove public --acl
- public runtime (#540)
- fix: prevent dev server full builds
- Vue3 autocomplete (#541)
- fix: build for windows
- skip to (#545)
- fix: temporary fix for bad encoding in static build
- add [sync]/typo
- remove check for bad encoding
- fix: asyncData must return object
- fix: banner v-if
- fix: asyncData always returns object
- fix: dont try deploy on tests
- wip
- wip
- feat[tests]: add vitest and initial tests

## What does this PR do?

### Release notes
RRR Fixed a bug in an app...

## Notes to Reviewer

## Document Changes

2023-08-18 12:43 UTC, jeremytubbs requested changes
Please, add back tests github action for PRs.

2023-08-18 14:04 UTC, surgiie commented
> Please, add back tests github action for PRs.

Ooops, didnt even think about it. 😓 Will push a workflow soon.

2023-08-18 14:17 UTC, surgiie commented
@jeremytubbs I added the .github folder back in from the production branch.

2023-08-18 17:55 UTC, jeremytubbs approved these changes

2023-08-21 15:07 UTC, nate998877 approved these changes

2023-08-21 15:26 UTC, merged