Retry is gross
DirectEmployers/microsite-js pull request #58
Opened 2021-01-21 06:43 UTC by nate998877

###What does it do?
Removes the retry method from Helpers and appgooglelocationautocomplete.

###notes to reviewer
I don't think the code would handle things well if google refused to load. Consider wrapping is try/catch. Although onload may never trigger?

2021-01-21 17:39 UTC, surgiie commented on src/components/Search/AppGoogleLocationAutocomplete.vue
> +            return window?.google?.maps?.places
This returns `undefined` on the inital load or an object  when it is loaded, the name implies that it returns a boolean determining if the places api has loaded, either rename the computed property or return a boolean.

2021-01-21 17:41 UTC, surgiie requested changes
This only works on the initial load of the autocomplete when you first open "Commute Search" modal. If you do  a commute search and reopen the modal and try to change your commute location, it doesnt autocomplete anymore.

This is because you need to reinit the autocomplete during the `updated` event:

```js
updated(){
    this.initAutocomplete()
}
```

2021-01-25 14:21 UTC, jeremytubbs commented on src/components/Search/AppGoogleLocationAutocomplete.vue
>  import {get} from "lodash"
unused import

2021-01-25 14:46 UTC, jeremytubbs requested changes
Can we rename this component to `AppGooglePlacesAutocomplete` since it is using the places api?

Pre-existing Issues (need to check out QC to confirm)
- changing input without selecting from the autocomplete dropdown does not clear the commute form coords
- commute search only works once per hard page refresh
     - after doing a commute search then reopening the modal to do another commute search the Google Places API autocomplete does not work
     - after doing a commute search and hitting clear all the and attempting to do another commute search the Places API autocomplete does not work

Improvements
- form submit button should be disabled if the user has not selected from the autocomplete and coords are available to do the search

2021-01-26 18:03 UTC, surgiie approved these changes
Approving with one change to make per Jeremy's feeback.

Coords are not cleared when the user is typing in the autocomplete input in commute search form.

You can fix this by adding `@input="input.coords = ''"` directly on the `AppGooglePlacesAutocompleteInput` in the commute search form.

You also have conflicts/need to merge latest QC.

2021-01-26 20:01 UTC, nate998877 commented
> Approving with one change to make per Jeremy's feeback.
> 
> Coords are not cleared when the user is typing in the autocomplete input in commute search form.
> 
> You can fix this by adding `@input="input.coords = ''"` directly on the `AppGooglePlacesAutocompleteInput` in the commute search form.
> 
> You also have conflicts/need to merge latest QC.

I can add your recommended fix, but I still cannot replicate this bug, which is frustrating.

2021-01-27 19:09 UTC, surgiie commented
> > Approving with one change to make per Jeremy's feeback.
> > Coords are not cleared when the user is typing in the autocomplete input in commute search form.
> > You can fix this by adding `@input="input.coords = ''"` directly on the `AppGooglePlacesAutocompleteInput` in the commute search form.
> > You also have conflicts/need to merge latest QC.
> 
> I can add your recommended fix, but I still cannot replicate this bug, which is frustrating.

Its not really a visual bug, but you can see it in the vue dev tools. When you type in commute search location input, the coords on the "input" in provider  do not clear.

2021-02-01 20:34 UTC, jeremytubbs approved these changes

2021-02-01 20:35 UTC, merged