[PD-9012] robots
DirectEmployers/microsite-js pull request #583
Opened 2023-09-15 19:21 UTC by nate998877

## What does this PR do?
Adds a section to the nuxtBuild to write the contents of the module option robotsTxt to robots.txt

Associated PR -

2023-09-15 20:35 UTC, surgiie requested changes

2023-09-15 20:35 UTC, surgiie commented on src/services/nuxtModule.js
> +            fs.writeFileSync(
Wrap this in an if statement that checks if `moduleOptions.robotsTxt` is set, otherwise you'll write a blank robots.txt file to s3.

2023-09-18 18:38 UTC, jeremytubbs approved these changes

2023-09-19 20:17 UTC, surgiie approved these changes

2023-09-19 21:06 UTC, merged