[PD-6885] two button pagination
DirectEmployers/microsite-js pull request #60
Opened 2021-01-25 16:13 UTC by nate998877

###What does this PR do?
This adds another pagination component that uses a simpler 2 button design

2021-01-26 18:49 UTC, surgiie requested changes
Looks good for the most part but I made a few comments for changes.

2021-01-26 18:49 UTC, surgiie commented on src/components/AppTwoButtonPagination.vue
> +<template>
I prefer that this component was called `AppSimplePagination` 

We also now have 3 pagination components, I would also prefer we group these into a `Pagination` directory to add better organization to the the components directory.

2021-01-26 18:49 UTC, surgiie commented on src/components/AppTwoButtonPagination.vue
> +        page {{currentPage}}
I dont think we should worry about showing the current page.

I would let the implementer decide with a slot:

```html
<slot :current-page="currentPage"></slot>
```

2021-01-26 18:49 UTC, surgiie commented on src/components/AppTwoButtonPagination.vue
> +            Back
Adds slots to allow customization of the `Back` and `Next` text via slots. This will allow people to use custom text or arrow icons as needed.

2021-01-29 16:26 UTC, nate998877 commented on src/components/AppTwoButtonPagination.vue
> +<template>
I will leave moving things until after Jeremy's PR on that. Have renamed though.

2021-02-01 20:43 UTC, jeremytubbs commented on src/components/AppTwoButtonPagination.vue
> +        page {{currentPage}}
I agree.. but I would just make a default empty slot `<slot />`

2021-02-01 20:43 UTC, jeremytubbs commented on src/components/AppTwoButtonPagination.vue
> +<template>
Please go ahead a move the pagination components into a folder.

2021-02-01 20:46 UTC, jeremytubbs requested changes
- remove `page #` and add an empty slot
- move the three components into a pagination folder

2021-02-03 17:33 UTC, surgiie commented
@nate998877 Just realized this will need documentation changes.

Can you make a PR in the docs repo, that updates docs for these changes.

https://github.com/DirectEmployers/microsite-docs

2021-02-03 18:48 UTC, nate998877 commented
> @nate998877 Just realized this will need documentation changes.
> 
> Can you make a PR in the docs repo, that updates docs for these changes.
> 
> https://github.com/DirectEmployers/microsite-docs

It's been a low priority item for me. I'll get on that now!

2021-02-04 18:56 UTC, surgiie approved these changes

2021-02-04 18:57 UTC, merged