[PD-6856] old to new redirect
DirectEmployers/microsite-js pull request #70
Opened 2021-02-10 17:18 UTC by nate998877

## What does this PR do?
This PR adds support for using "old" format filter urls.

## Notes to Reviewer
This whole thing feels really janky and while it does appear to work appropriately. I would imagine it has the potential to introduce lots of weird edge cases. Test thoroughly!

## Associated backend PR
TODO : Open backend PR and update with link

2021-02-11 22:25 UTC, jeremytubbs commented on src/components/Search/Providers/mixins/provider.js
> +            if(this.getUrlExtraDataObject(this.$route.params)){
Can you please explain these changes?

2021-02-15 17:03 UTC, nate998877 commented on src/components/Search/Providers/mixins/provider.js
> +            if(this.getUrlExtraDataObject(this.$route.params)){
This might need to be changed since it comes from a point of naivety with how the urls work, but when using the old url format we have to prevent route params from entering input. I don't see any instances of using url slugs with the new format, so I assumed they'd only be applicable for old urls. Thus I just completely omit them and instead handle them as extra data.

2021-02-19 14:53 UTC, jeremytubbs requested changes
Can you close this PR or just make a PR with only expanded solr_queries? And the App404 change. We will work on the provider changes later.

2021-02-19 14:56 UTC, nate998877 commented
PR is no longer applicable

2021-02-19 14:56 UTC, closed without merging