[PD-7007] paginations use URL params
DirectEmployers/microsite-js pull request #92
Opened 2021-03-09 20:30 UTC by nate998877

## What does this PR do?
This changes the pagination components from using buttons to links

## Notes to Reviewer
It feels like a lot of code was removed. I don't think it's used at this point, but it's worth ensuring that's the case.

## Document Changes
I don't think we document the mechanisms by which the components work do we? If so let me know and I'll add a pr.

2021-03-11 15:30 UTC, surgiie requested changes

2021-03-11 15:30 UTC, surgiie commented on src/components/Pagination/AppPagination.vue
> +            let regex = /(\?page=)(\d+)|(&page=)(\d+)/
Not sure a regex is really needed, feels a bit more complex than it has to be.
Couldnt you just utilize the `$route.query` object ? I think the function could be simplified to

```js
import buildUrl from "axios/lib/helpers/buildURL"

....

link(page){
    if(isNaN(page)){
        return ""
    }
    let query = this.$route.query
    query.page = page

    return buildUrl(this.$route.path, query)
},

```

2021-03-11 15:30 UTC, surgiie commented on src/components/Pagination/AppPagination.vue
> +                    :to="link(nextPage)"
I would honestly make this a dynamic component because right now the `...` becomes a clickable link to `/jobs` 

I would just make it a span if the page === '...'

```
<component :is="page == '...' ? 'span': 'g-link'"
   .....
>
</component>
```

2021-03-11 15:30 UTC, surgiie commented on src/components/Pagination/AppSimplePagination.vue
> +        link(page){
Same issue here, utilize `$route.query`

2021-03-11 15:30 UTC, surgiie commented on src/components/Search/Providers/mixins/provider.js
> -        setInput(filter) {
I think this function should remain to allow Zarif to still use it in the slot/on his end.

2021-03-12 14:08 UTC, jeremytubbs requested changes
Please merge quality-control... never mind I did it.

2021-03-12 14:16 UTC, jeremytubbs requested changes
When on `http://localhost:8080/jobs` the pagination is not allowing me to click http://localhost:8080/jobs?page=1 and when I go to http://localhost:8080/jobs?page=3 ... page 2 is missing.

![image](https://user-images.githubusercontent.com/548888/110951872-8d1c6e00-8313-11eb-8bfb-1134bd3187c1.png)

2021-03-12 14:19 UTC, jeremytubbs commented
Also it is allowing me to click the 1 when on `page=1`

2021-03-15 19:18 UTC, surgiie approved these changes

2021-03-15 20:43 UTC, jeremytubbs approved these changes

2021-03-15 20:54 UTC, merged